import streamlit as st
from datetime import datetime


def generate_report():

    st.header("📄 AgriDSS_AI Report")

    data = st.session_state.get("user_data")
    weather = st.session_state.get("weather_data")
    ndvi = st.session_state.get("ndvi_value")

    if not data:
        st.warning("No data available. Please complete Farm Input and Run Analysis first.")
        return

    # -------------------------
    # WEATHER DATA SAFE HANDLING
    # -------------------------
    if weather:
        temperature = weather.get("temperature", "N/A")
        humidity = weather.get("humidity", "N/A")
        condition = weather.get("condition", "N/A")
    else:
        temperature = humidity = condition = "N/A"

    # -------------------------
    # NDVI STATUS
    # -------------------------
    if ndvi is None:
        ndvi_status = "N/A"
    else:
        if ndvi > 0.6:
            ndvi_status = "Healthy Vegetation"
        elif ndvi > 0.3:
            ndvi_status = "Moderate Vegetation"
        else:
            ndvi_status = "Low Vegetation"

    # -------------------------
    # REPORT STRING (ONLY TEXT)
    # -------------------------
    report = f"""
==================================================
                AGRIDSS_AI REPORT
==================================================

Report Date:
{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

------------ FARM INFORMATION ------------

District : {data.get('district', 'N/A')}
Tehsil   : {data.get('tehsil', 'N/A')}
Crop     : {data.get('crop', 'N/A')}
Area     : {data.get('area', 'N/A')}

------------ WEATHER ANALYSIS ------------

Temperature : {temperature} °C
Humidity    : {humidity} %
Condition   : {condition}

------------ NDVI ANALYSIS ------------

NDVI Value  : {ndvi}
Status      : {ndvi_status}

---------- AI RECOMMENDATION ----------

    # -------------------------
    # AI INSIGHT (SEPARATE UI SECTION - CORRECT WAY)
    # -------------------------
    st.subheader("🌾 AI Recommendation")

    if ndvi is None:
        st.warning("NDVI not available for AI analysis.")
        return

    if ndvi < 0.2:
        st.error("🔴 Critical stress detected. Immediate irrigation required.")

    elif ndvi < 0.4:
        st.warning("🟡 Moderate stress observed. Irrigation recommended soon.")

    elif ndvi < 0.6:
        st.info("🟢 Crop is stable with mild stress risk.")

    else:
        st.success("🌿 Excellent vegetation health detected.")

    # -------------------------
    # SHOW REPORT
    # -------------------------
    st.text_area(
        "Generated Report",
        report,
        height=450
    )

==================================================
This report was generated by AgriDSS_AI System
==================================================
"""
